version: '3'
services:
  app1:
    build:
      context: .
    hostname: app1
    platform: linux/amd64
    ports:
      - "8080:8080"
    environment:
      PROXY_HOSTNAME: "sentinel-cogs.s3.amazonaws.com"
  app2:
    build:
      context: .
    platform: linux/amd64
    hostname: app2
    ports:
      - "8081:8080"
    environment:
      PROXY_HOSTNAME: "sentinel-cogs.s3.amazonaws.com"
  app3:
    build:
      context: .
    platform: linux/amd64
    hostname: app3
    ports:
      - "8082:8080"
    environment:
      PROXY_HOSTNAME: "sentinel-cogs.s3.amazonaws.com"
  nginx:
    image: nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf