version: '3'
services:
  proxy1:
    build:
      context: .
    platform: linux/amd64
    ports:
      - "8080:4000"
  proxy2:
    build:
      context: .
    platform: linux/amd64
    ports:
      - "8081:4000"
  proxy3:
    build:
      context: .
    platform: linux/amd64
    ports:
      - "8082:4000"